name: Update README

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Get registration date
        id: get_date
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          DATE=$(bash .github/scripts/get_first_commit.sh "${{ github.repository_owner }}")
          echo "FIRST_COMMIT_DATE=$DATE" >> $GITHUB_ENV

      - name: Make scripts executable
        run: chmod +x .github/scripts/*.sh

      - name: Get external commits
        id: external_commits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          EXTERNAL=$(./.github/scripts/get_external_commits.sh "${{ github.repository_owner }}")
          echo "EXTERNAL_COMMITS=$EXTERNAL" >> $GITHUB_ENV
      
      - name: Update README
        env:
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIRST_COMMIT_DATE: ${{ env.FIRST_COMMIT_DATE }}
          TOTAL_COMMITS: ${{ env.TOTAL_COMMITS }}
          YEAR_COMMITS: ${{ env.YEAR_COMMITS }}
          EXTERNAL_COMMITS: ${{ env.EXTERNAL_COMMITS }}
        run: |
          python3 .github/scripts/update_readme.py
          cat README.md
          
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "📅 Automatic README update"
          git push
